#!/bin/bash

declare -a params=()
while [[ $1 ]]; do
    if [[ $1 == "" || $1 == -h* ]]; then
        echo 'Does a simple "git add" followed by "git status".'
        echo 'Usage: gip-add <path1 [path2 [...pathN]]>'
        exit 0
    elif [[ $1 == --echo || $1 == -echo ]]; then
        echo=1
    else
        params+=("$1")
    fi
    shift
done
if [[ $echo ]]; then
    echo git add "${params[@]}" "&&" git status
else
    git add "${params[@]}" && git status
fi